SET search_path TO primmo_bash_dev, public;

/*
 * LES TRIGGERS SONT DEFINIS APRES LES FONCTIONS QU'ILS SHOOTENT, A LA FIN DU FICHIER : TRIGGERS.sql
 * 
 * Try Neon, mixing git an d pg ... 
*/


-- TODO :
-- + table pour les biens
-- + table pour les actifs
-- interruption de charges
drop table if exists compte cascade;
drop table if exists users cascade;
drop table if exists bien cascade;
drop table if exists actif cascade;
drop table if exists locataire cascade;
drop table if EXISTS quittance cascade;
drop table if exists type_charge cascade;
drop table if exists charges cascade;
drop table if exists regularisation cascade;
drop table if exists regularisation_statut cascade;
drop table if exists ligne_regularisation cascade;
drop table if exists ligne_regularisation_type cascade;

DROP TYPE IF EXISTS denomination; 

-- table de configuration de l'app !
CREATE TABLE IF NOT EXISTS compte (
	id integer generated by default as identity primary key,
	label text NOT NULL,
	ts_created_at timestamp NOT NULL DEFAULT now(),
	fk_created_by SMALLINT REFERENCES compte ON DELETE NO ACTION ON UPDATE CASCADE,
	config hstore NULL, -- quotas /// quota_disk / quota_user
	note text NOT NULL
);


CREATE TABLE IF NOT EXISTS users (
	id integer generated by default as identity primary key,
	fk_compte SMALLINT REFERENCES compte ON DELETE NO ACTION ON UPDATE CASCADE, 
	nom text NOT NULL,
	prenom text NOT NULL,
	email char(255) NOT NULL,
	password char(255) NOT NULL,
	note text NOT NULL
);

CREATE TABLE IF NOT EXISTS bien(
  id integer generated by default as identity primary key,
  fk_compte SMALLINT REFERENCES compte ON DELETE NO ACTION ON UPDATE CASCADE, 
  label text not null,
  surface_totale SMALLINT NOT NULL,
  mise_en_service date NOT NULL,
  teom numeric,
  config hstore NULL, -- charges obligatoires, méthode de calcul ( factures au réel par défault ) , gestion estimatif / 
  -- est_standart boolean not null default true,
  note text null
);


CREATE TABLE IF NOT EXISTS actif (
  id integer generated by default as identity primary key,
  fk_bien integer REFERENCES bien ON DELETE NO ACTION ON UPDATE CASCADE, 
  label text not null,
  surface SMALLINT NOT NULL,
  adresse TEXT,
  note text null
);

--CREATE EXTENSION btree_gist;
CREATE TYPE denomination AS ENUM ( 'Mr', 'Melle', 'Mme' );

CREATE TABLE IF NOT EXISTS locataire(
  id integer generated by default as identity primary key,
  denomination denomination NOT NULL DEFAULT 'Mr',
  prenom TEXT NOT NULL,
  nom TEXT NOT NULL,
  email TEXT NULL,
  fk_actif int REFERENCES actif ON DELETE NO ACTION ON UPDATE CASCADE,
  periode_occupation daterange NOT NULL,
  loyer_mensuel_hc numeric NOT NULL,
  montant_caution NUMERIC NOT NULL,
  provision_charge_mensuelle numeric NOT NULL,
  loyer_total numeric GENERATED ALWAYS AS( loyer_mensuel_hc + provision_charge_mensuelle ) STORED,
  date_depart_reelle date NULL DEFAULT NULL, -- antérieure à la date de début du bail / impacte les chambres disponibles
  date_cloturabilite_effective date NULL DEFAULT NULL,
  est_entree_directe boolean not null default true,
  est_charge_cloturable boolean not null default false,
  est_charge_cloture boolean not null default false, -- si ON a une date de fin de bail
  note text NULL,
  EXCLUDE USING gist (
    fk_actif WITH =,
    periode_occupation WITH &&
  )
);



-- idéalement les quittances référencent la table : locataire_loue_actif
CREATE TABLE IF NOT EXISTS quittance (
	id int generated by default as identity primary key,
	fk_locataire int REFERENCES locataire ON DELETE NO ACTION ON UPDATE CASCADE,
	ts_date_emission timestamp WITH time ZONE NOT NULL DEFAULT now(),
	-- periode_couverte daterange NOT NULL, ( works hard with same date. Included or Not. Included add 1 day to normalize. Excluded returns 'empty'. Go to tsrange but inject time into a type used to define periods over a month ... )
	periode_couverte char( 7 ) NOT NULL,
	numero_quittance smallserial NOT NULL,
	contenu TEXT,
	nom_fichier text,
	note text NULL
);


-- amélioration de l'architecture pour relouer au meme locataire ... Belle refacto en perspective !
CREATE TABLE IF NOT EXISTS location (
  id int generated by default as identity primary key,
  fk_locataire int REFERENCES locataire ON DELETE NO ACTION ON UPDATE CASCADE,
  fk_actif int REFERENCES actif ON DELETE NO ACTION ON UPDATE CASCADE,
  bail lo,
  periode_occupation daterange NOT NULL,
  loyer_mensuel_hc numeric NOT NULL,
  montant_caution NUMERIC NOT NULL,
  provision_charge_mensuelle numeric NOT NULL,
  loyer_total numeric GENERATED ALWAYS AS( loyer_mensuel_hc + provision_charge_mensuelle ) STORED,
  date_depart_reelle date NULL DEFAULT NULL, -- antérieure à la date de début du bail / impacte les chambres disponibles
  date_cloturabilite_effective date NULL DEFAULT NULL,
  est_entree_directe boolean not null default true,
  note text NULL
);
  
  


CREATE TABLE IF NOT EXISTS type_charge(
  id int generated by default as identity primary key,
  label text not null,
  montant_forfaitaire_journalier_individuel numeric null,
  -- est_standart boolean not null default true,
  note text null
);
-- TYPE CHARGE :: MASTER DATA

INSERT INTO type_charge ( id, LABEL, note ) VALUES ( 9999, 'exception', 'utilisé pour les facturations individuelles' ), ( 8888, 'TEOM', 'périodicité annuelle' );

INSERT INTO type_charge ( LABEL, montant_forfaitaire_journalier_individuel ) VALUES ( 'eau', 0.65 ), ( 'gaz', null ), ( 'electricité', null ), ( 'pétrole', null ), ( 'pellet', null ), ( 'bois', null ), ( 'fioul', null );
-- INSERT INTO type_charge ( label ) VALUES ( 'solar' );
-- SELECT nextval( 'primmo_bash_dev.type_charge_id_seq' );


-- TODO : add rule : if est_fractionnable, fk_locataire is null ( if fk_clocataire is not null -> charge dédiée au locataire )
CREATE TABLE IF NOT EXISTS charges(
  id integer generated by default as identity primary key,
  fk_type_charge smallserial not null references type_charge on update cascade on delete no action,
  fk_locataire integer references locataire( id ) on update cascade on delete no action, --> si not null, charge non fractionnable, individuelle
  fk_bien integer REFERENCES bien ON UPDATE CASCADE ON DELETE NO ACTION,
  date_emission timestamp with time zone not null,
  periode daterange,
  montant numeric not null,
  nb_jours smallint GENERATED ALWAYS AS ( upper( periode ) - lower( periode ) ) STORED,
  montant_journalier real GENERATED ALWAYS AS ( montant / ( upper( periode ) - lower( periode ) ) ) STORED,
  reference_facture TEXT NULL,
  contenu pdf NULL,
  file_name text NULL,
  note TEXT NULL,
  CONSTRAINT periode_not_null CHECK ( ( fk_type_charge = 9999 AND periode IS NULL ) OR ( fk_type_charge <> 9999 AND periode IS NOT NULL )),
  EXCLUDE USING  gist(
    fk_type_charge with =,
    periode with &&
  )
);



/*
 * Valeur Ajoutée. L'ordre et la quantité des régularisations permet de déterminer le 'cycle de vie' d'une régularisation.
 * KISS ?
 * On garde simplement le marquer 'est_cloture' côté locataire.  
 * 
TRUNCATE primmo_bash_dev.regularisation_etape RESTART IDENTITY;
CREATE TABLE IF NOT EXISTS primmo_bash_dev.regularisation_etape (
  id smallserial PRIMARY KEY, --int generated by default as identity ( START WITH 1 ) primary key,
  label text not NULL,
  note text null
);
-- TYPE ETAPE_REGULARISATION   :: MASTER DATA
INSERT INTO primmo_bash_dev.regularisation_etape ( label ) VALUES ( 'initiale' ), ( 'intermédiare' ), ( 'finale' );
-- fk_regularisation_etape smallserial REFERENCES primmo_bash_dev.regularisation_etape ( id ) on update cascade on delete no action,
*/

-- TRUNCATE primmo_bash_dev.regularisation_statut RESTART IDENTITY;
CREATE TABLE IF NOT EXISTS regularisation_statut (
  id int generated by default as identity ( START WITH 1 ) primary key,
  label text not NULL,
  note text null
);
-- TYPE STATUT_REGULARISATION   :: MASTER DATA
INSERT INTO regularisation_statut ( label, note ) VALUES 
	( 'Naturelle', 'Régularisation basée uniquement sur des factures ( requises )' ), 
	( 'Hybride', 'Régularisation dont une partie est naturelle et une autre est synthétique' ),
	( 'Synthétique', 'Régularisation intégralement non basée sur des factures. Forfait. Négociation. Moyenne ...' );


CREATE TABLE IF NOT EXISTS regularisation(
  id integer generated by default as identity primary key,
  fk_locataire serial REFERENCES locataire ( id ) on update cascade on delete no action,
  -- fk_regularisation_statut smallserial REFERENCES primmo_bash_dev.regularisation_statut ( id ) on update cascade on delete no action,
  ts_date_regularisation timestamp with time zone not null,
  credit_bailleur_sur_provision numeric generated always as ( total_charges_reelles_individuelles - total_charges_provisionnees ) stored,
  montant_reel_demande numeric null,
  total_charges_provisionnees numeric not null,  -- > rename : solde_intermediaire_charges_provisionnees  
  total_charges_reelles_individuelles NUMERIC null,
  total_charges_reelles_globalles numeric null,
  -- est_finale boolean not null default false,
  -- est_forcee_moyenne_reelle boolean not null default false,
  -- est_forcee_moyenne_arbitraire boolean not null default false,
  -- est_forcee_forfaitaire boolean not null default false, 
  -- est_reelle boolean not null default false,
  est_soldee boolean not null default false,
  note text null
  );
COMMENT ON TABLE regularisation IS 'Les colonnes est_forcee_* enregistrent le fait qu''une régularisation soit forcée ( avec un calcul basée, sur une moyenne réelle, arbitraire, ou sur un forfait. Dans ce cas, un arrangement a été trouvé et le recouvrement factures / période_occupation n''est pas obligatoire. Si une régularisation est forcée, elle est à priori finale. Enfin, si une régularisation est forcée, aucune ligne_regularisation ne doit exister.';
/*
INSERT INTO regularisation ( fk_locataire, ts_date_regularisation, periode_couverte, montant_regularisation, total_charges_provisionnees, total_charges_reelles, est_finale, '' ) VALUES 
  ( 1, now(), '[2023-10-07, 2023-12-06]', 100.00, 30.00, 120.00, true, '' );
*/

CREATE TABLE IF NOT EXISTS ligne_regularisation_type (
  id smallserial PRIMARY KEY, --int generated by default as identity ( START WITH 1 ) primary key,
  label text not NULL,
  note text null
);
INSERT INTO ligne_regularisation_type ( label, note ) VALUES
	( 'Naturelle', 'Ligne de régularisation basée intégrallement sur facture.' ),
	( 'Synthétique Arbitraire', 'Ligne de régularisation basée sur un montant journalier arbitraire.' ),
	( 'Synthétique Moyenne Facture', 'Ligne de régularisation dont le montant individuel de la zone aveugle repose sur une moyenne des factures connues sur la propriété à date.' ),
	( 'Synthétique Moyenne Bail', 'Ligne de régularisation dont le montant individuel de la zone aveugle repose sur une moyenne des factures connues sur le bien à date.' );
	-- ( 'Synthétique Forfaitaire', 'Ligne de régularisation dont la zone aveugle repose sur un forfait journalier individuel' );

CREATE TABLE IF NOT EXISTS ligne_regularisation(
  id integer generated by default as identity primary key,
  fk_regularisation serial REFERENCES regularisation ( id )  on update cascade on delete no action,
  fk_type_charge serial REFERENCES type_charge ( id )  on update cascade on delete no action,
  fk_ligne_regularisation_type smallserial REFERENCES ligne_regularisation_type ( id )  on update cascade on delete no ACTION,
  montant_total numeric not null, -- keep ?
  montant_individuel numeric not null,
  ts_date_arret timestamp with time zone null,
  note text null
  );
COMMENT ON TABLE ligne_regularisation IS 'Cette table stocke le détail d''une réguularisation de charge. Seules les lignes présentes nécessitent un rappel / clôture de charge';
COMMENT ON COLUMN ligne_regularisation.ts_date_arret IS 'Cette colonne stocke la date butoir jusqu a laquelle le calcul des charges a pu se faire. Si la facture est absente de la régularisation en cours, ce qui peut arriver avec l eau, la date butoir est la date de fin de periode de la dernière facture.';



-- include DATA
RESET search_path;

